language: java

jdk:
  - openjdk11

git:
  submodules: false

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - |
    cat >~/.netrc <<!
    machine github.com
    login $GITHUB_TOKEN
    !
  - git submodule update --init --recursive
  - cd ./backend/
  - chmod +x gradlew

before_deploy:
  - zip -r oclothes
  - mkdir -p deploy
  - mv oclothes.zip deploy/oclothes.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    github-token: $GITHUB_TOKEN
    bucket: oclothes-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: https://github.com/today-clothes/my-closet.git
      branch: main

notifications:
  email:
    recipients:
      -iamsemi1115@gmail.com
