spring:
  profiles:
    group:
      "prod": "jwt,oauth,mail"
      "local": "jwt,oauth,mail"
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql : true
  data:
    web:
      pageable:
        one-indexed-parameters: true

