spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace